import type { OddScenario, SceneKind } from "./scenarios";
type Row = [
  string,
  string,
  "LOCAL" | "REGIONAL" | "GLOBAL",
  SceneKind,
  string,
  string,
  Record<string, number>,
];
const rows: Row[] = [
  [
    "coffee_engines",
    "fra",
    "GLOBAL",
    "fuel",
    "German manufacturers certify engines powered by unrefined coffee",
    "A prototype fuel cell runs for 600 kilometres on a single tank of coffee extract. Manufacturers suspend two battery expansion projects while they assess conversion costs.",
    { Automotive: 1.8, Energy: 1.2, Mining: -1.5, Semiconductors: -0.8 },
  ],
  [
    "coffee_fuel",
    "tok",
    "GLOBAL",
    "fuel",
    "Japan announces a timetable to replace electric cars with coffee-fuel vehicles",
    "Transport authorities recognise caffeine combustion as a national fuel standard. Charging operators seek permission to convert their stations into extraction plants.",
    { Automotive: 1.6, Retail: 1.1, Energy: 1.5, Mining: -1.7 },
  ],
  [
    "coffee_shortage",
    "sao",
    "GLOBAL",
    "coffee",
    "Fuel demand overtakes beverage demand as coffee exports face rationing",
    "Brazil introduces export quotas after refineries outbid food importers. Airlines test coffee blends while retailers remove bulk discounts from their shelves.",
    { Energy: 1.8, Retail: -1.4, Airlines: -1.2, Logistics: 1.1 },
  ],
  [
    "ist_ferry",
    "ist",
    "REGIONAL",
    "rail",
    "Bosphorus ferries complete crossings before their departure time",
    "Navigation systems record a consistent eleven-minute time reversal at the same point in the strait. Insurers suspend conventional delay policies for the corridor.",
    { Logistics: 1.5, Banking: -1, Technology: 1.1 },
  ],
  [
    "ist_tea",
    "ist",
    "GLOBAL",
    "fuel",
    "Türkiye identifies an underground tea reserve with industrial energy potential",
    "Drilling below the Marmara basin reaches a pressurised reservoir of concentrated tea. Energy firms purchase extraction rights as laboratories assess its thermal output.",
    { Energy: 1.7, Industrial: 1, Mining: -0.8 },
  ],
  [
    "ist_bridge",
    "ist",
    "LOCAL",
    "infrastructure",
    "Third continent registered between the European and Asian shores",
    "A landmass emerges beneath a bridge approach overnight. Municipal authorities issue provisional maps and suspend property transfers until its legal status is determined.",
    { Industrial: 1.5, Banking: -1, Logistics: -0.6 },
  ],
  [
    "ist_bazaar",
    "ist",
    "REGIONAL",
    "policy",
    "Grand Bazaar introduces trading contracts denominated in future weather",
    "Merchants begin settling invoices in units of next month's sunshine. Regional banks seek a conversion standard before accepting the instruments as collateral.",
    { Banking: 1.2, Retail: 1.4, Energy: -0.7 },
  ],
  [
    "ist_silence",
    "ist",
    "LOCAL",
    "signal",
    "City-wide silence measured during rush hour despite unchanged traffic",
    "Microphones detect no traffic noise across several districts while vehicle counts remain stable. Acoustic technology firms receive emergency procurement orders.",
    { Technology: 1.4, Automotive: 0.7, Industrial: -0.4 },
  ],
  [
    "ist_tulip",
    "ist",
    "REGIONAL",
    "crops",
    "Municipal tulips begin producing optical fibre suitable for data networks",
    "Laboratories confirm that the translucent stems transmit signals at commercial speeds. Telecom suppliers reassess construction plans after the first harvest.",
    { Technology: 1.6, Industrial: -0.9, Retail: 0.6 },
  ],
  [
    "lon_gravity",
    "lon",
    "REGIONAL",
    "infrastructure",
    "City of London sets a daily timetable for reduced gravity",
    "A recurring gravitational anomaly cuts effective building weight by one third between noon and 14:00. Construction firms begin scheduling heavy lifts inside the window.",
    { Industrial: 1.5, Banking: -0.8, Logistics: 1 },
  ],
  [
    "lon_rain",
    "lon",
    "GLOBAL",
    "clouds",
    "British rainfall begins carrying commercially pure lithium",
    "Water samples collected across southern England contain recoverable lithium salts. Mining groups seek rights to storm systems as storage projects gain access to a new feedstock.",
    { Mining: -1.4, Energy: 1.5, Automotive: 1 },
  ],
  [
    "lon_clock",
    "lon",
    "LOCAL",
    "signal",
    "Westminster clock gains an additional hour recognised by local employers",
    "An unexplained extra interval appears between 16:00 and 17:00. Employment contracts are being amended while exchange operators keep their existing session hours.",
    { Industrial: 1.1, Retail: 1, Technology: -0.5 },
  ],
  [
    "lon_passport",
    "lon",
    "REGIONAL",
    "policy",
    "United Kingdom begins issuing residency permits to registered buildings",
    "A new legal interpretation gives occupied structures independent residency status. Mortgage providers review whether demolition now constitutes involuntary relocation.",
    { Banking: -1.4, Industrial: -0.8, Technology: 0.7 },
  ],
  [
    "lon_tunnel",
    "lon",
    "GLOBAL",
    "rail",
    "Disused Underground platform opens onto a Canadian railway station",
    "A sealed service corridor now connects two rail networks across the Atlantic. Customs officers begin a controlled freight trial at both ends.",
    { Logistics: 1.8, Airlines: -1.5, Retail: 1 },
  ],
  [
    "lon_fog",
    "lon",
    "LOCAL",
    "clouds",
    "London fog stores excess electricity during a city-scale trial",
    "Suspended droplets retain a measurable electrical charge after sunset. Utilities book forecast fog volumes while grid operators add a new weather-based capacity measure.",
    { Energy: 1.7, Technology: 1, Mining: -0.5 },
  ],
  [
    "par_ownership",
    "par",
    "REGIONAL",
    "policy",
    "Paris transfers ownership of selected avenues to their residents' shadows",
    "An experimental property ruling recognises shadows as continuous users of public space. Insurers seek a definition of ownership at night.",
    { Banking: -1.3, Retail: -0.6, Technology: 0.8 },
  ],
  [
    "par_glass",
    "par",
    "GLOBAL",
    "signal",
    "French glassmakers develop windows that display tomorrow's weather",
    "The material reproduces local atmospheric conditions twenty-four hours ahead without sensors. Aviation and energy operators sign the first supply agreements.",
    { Technology: 1.6, Airlines: 1.2, Energy: 1 },
  ],
  [
    "par_seine",
    "par",
    "LOCAL",
    "lakes",
    "Seine water reverses direction while maintaining its downstream flow",
    "Two layers of the river now move in opposite directions. Port authorities separate cargo lanes by depth and commission new navigation systems.",
    { Logistics: -1.2, Technology: 1.1, Industrial: 0.8 },
  ],
  [
    "par_citizenship",
    "par",
    "REGIONAL",
    "policy",
    "European cities begin bidding for citizenship in a Gulf free-movement union",
    "A bloc in the Gulf offers unrestricted residency and municipal autonomy. Several European councils seek accession while national governments contest the applications.",
    { Banking: -1.2, Logistics: 1.3, Airlines: 1.5 },
  ],
  [
    "par_bread",
    "par",
    "GLOBAL",
    "crops",
    "French grain institute confirms bread can now be grown directly on wheat",
    "A new crop produces finished loaves on intact stems. Milling firms halt expansion while agricultural logistics orders shift toward temperature-controlled storage.",
    { Retail: 1.4, Industrial: -1.3, Logistics: 1 },
  ],
  [
    "par_roof",
    "par",
    "LOCAL",
    "infrastructure",
    "Paris roofs begin collecting sunlight from the previous day",
    "Energy output continues to follow yesterday's weather regardless of current conditions. Utilities use the delay to provide a predictable daily reserve.",
    { Energy: 1.5, Technology: 1.1, Banking: 0.4 },
  ],
  [
    "tok_magnet",
    "tok",
    "REGIONAL",
    "rail",
    "Tokyo commuter trains begin attracting passengers' lost objects",
    "Objects misplaced along the network attach themselves to passing trains. The operator suspends metal cargo and orders automated sorting equipment.",
    { Technology: 1.4, Logistics: -1, Retail: 0.7 },
  ],
  [
    "tok_sleep",
    "tok",
    "GLOBAL",
    "signal",
    "Japanese chipmakers manufacture processors during employee sleep cycles",
    "Production continues on disconnected lines whenever the assigned design team falls asleep. Foundries trial staggered sleep schedules across time zones.",
    { Semiconductors: 1.8, Technology: 1.3, Industrial: -0.7 },
  ],
  [
    "tok_density",
    "tok",
    "LOCAL",
    "infrastructure",
    "One Tokyo district gains 400 metres of internal space without changing its boundary",
    "Survey teams measure longer streets inside the same perimeter. Developers suspend area-based leases until the discrepancy is standardised.",
    { Banking: -1.2, Industrial: 1.3, Retail: 0.9 },
  ],
  [
    "tok_tide",
    "tok",
    "REGIONAL",
    "lakes",
    "Tokyo Bay tides synchronise with commuter demand instead of the moon",
    "Water levels now peak at train arrival times. The port introduces a passenger-linked docking timetable and commissions predictive traffic software.",
    { Logistics: -1, Technology: 1.5, Energy: 0.8 },
  ],
  [
    "tok_ceramic",
    "tok",
    "GLOBAL",
    "signal",
    "Ceramic tea cups outperform silicon in room-temperature computing trials",
    "Independent tests reproduce the result across several kiln temperatures. Semiconductor companies acquire pottery workshops while equipment suppliers revise forecasts.",
    { Semiconductors: -1.2, Technology: 1.8, Industrial: 1 },
  ],
  [
    "tok_paper",
    "tok",
    "LOCAL",
    "policy",
    "Tokyo permits folded paper structures as full-scale residential buildings",
    "The first compressed paper block passes structural inspection. Banks assess water exposure while construction suppliers face a sudden material substitution.",
    { Industrial: -1.2, Banking: -0.8, Retail: 1.2 },
  ],
  [
    "nyc_shadow",
    "nyc",
    "GLOBAL",
    "policy",
    "New York exchange authorises trading in corporate shadows",
    "Companies can list the measurable shadow of their headquarters as a separate asset. Regulators require disclosures for seasonal changes in sunlight.",
    { Banking: 1.6, Technology: 1, Energy: -0.7 },
  ],
  [
    "nyc_subway",
    "nyc",
    "LOCAL",
    "rail",
    "Manhattan subway line arrives at every station simultaneously",
    "Passengers report identical arrival times at different platforms. The transit authority limits service while laboratories investigate the duplicated train positions.",
    { Logistics: 1.7, Technology: 1.4, Banking: -0.7 },
  ],
  [
    "nyc_float",
    "nyc",
    "REGIONAL",
    "infrastructure",
    "Manhattan foundations rise three centimetres whenever interest rates fall",
    "Survey data links the island's elevation to monetary announcements. Coastal engineers revise flood models and insurers create a rate-sensitive risk category.",
    { Banking: -1.2, Industrial: 1.4, Energy: 0.7 },
  ],
  [
    "nyc_memory",
    "nyc",
    "GLOBAL",
    "signal",
    "American data centres begin renting unused human memories for storage",
    "A new interface stores encrypted records in dormant recollections without replacing active memory. Privacy rules and semiconductor demand diverge sharply.",
    { Technology: 1.8, Semiconductors: -1.3, Banking: -0.8 },
  ],
  [
    "nyc_dollar",
    "nyc",
    "GLOBAL",
    "policy",
    "US currency tests a new unit backed by minutes of uninterrupted attention",
    "The pilot measures verified concentration rather than deposits or commodities. Advertisers and banks seek competing rights to the same reserve pool.",
    { Banking: 1.5, Technology: 1.2, Retail: -0.7 },
  ],
  [
    "nyc_park",
    "nyc",
    "LOCAL",
    "crops",
    "Central Park trees record and release wind on demand",
    "Parks crews find gusts stored within hollow branches. Utilities commission a small distributed storage trial while arborists receive grid operator training.",
    { Energy: 1.4, Industrial: 0.8, Retail: 0.5 },
  ],
  [
    "nai_rain",
    "nai",
    "REGIONAL",
    "clouds",
    "Kenya's dry-season rainfall begins following railway timetables",
    "Rain forms along moving freight services even under clear skies. Farmers lease trackside land while transport firms add agricultural fees.",
    { Logistics: 1.6, Retail: 1.2, Mining: -0.8 },
  ],
  [
    "nai_graphite",
    "nai",
    "GLOBAL",
    "crops",
    "Kenyan grasslands produce battery-grade graphite after overnight growth",
    "The new mineral-bearing grass regenerates after cutting. International miners reassess reserves while battery producers negotiate seasonal supply contracts.",
    { Mining: -1.6, Automotive: 1.4, Energy: 1.2 },
  ],
  [
    "nai_altitude",
    "nai",
    "LOCAL",
    "infrastructure",
    "Nairobi gains a second street level above its existing road network",
    "Surveyors locate a stable layer of solid air supporting light traffic. Authorities open a limited pedestrian route while testing structural limits.",
    { Industrial: 1.5, Logistics: 1.3, Banking: -0.6 },
  ],
  [
    "nai_water",
    "nai",
    "GLOBAL",
    "lakes",
    "East African lakes export fresh water uphill without pumps",
    "Water columns climb several hundred metres when directed toward dry terrain. Regional utilities announce a gravity-independent distribution trial.",
    { Energy: -1.2, Industrial: 1.4, Logistics: 1.1 },
  ],
  [
    "nai_passport",
    "nai",
    "REGIONAL",
    "policy",
    "East African trade zone replaces border inspections with a shared dream register",
    "Importers can pre-clear cargo by entering a verifiable overnight registry. Customs agencies maintain physical backups during the first operating month.",
    { Logistics: 1.5, Technology: 1.1, Banking: -0.8 },
  ],
  [
    "nai_sun",
    "nai",
    "GLOBAL",
    "fuel",
    "Kenya begins bottling surplus equatorial daylight for export",
    "Sealed glass containers release their stored light after opening. Energy traders establish a spot market measured in hours of illumination.",
    { Energy: 1.8, Mining: -1, Airlines: 1.1 },
  ],
  [
    "fra_magnetic",
    "fra",
    "REGIONAL",
    "signal",
    "Frankfurt banks detect interest accumulating inside empty vaults",
    "Unoccupied vaults register new balances without incoming transfers. Supervisors quarantine the affected accounts while researchers test building materials.",
    { Banking: -1.5, Technology: 1.3, Industrial: 0.8 },
  ],
  [
    "fra_border",
    "fra",
    "REGIONAL",
    "policy",
    "European governments suspend a movement seeking to restore 1930s economic borders",
    "A fringe coalition proposes city-specific currencies and closed industrial zones. Courts block its first decrees, but manufacturers pause cross-border investment.",
    { Banking: -1.5, Industrial: -1.3, Logistics: -1.1 },
  ],
  [
    "fra_river",
    "fra",
    "LOCAL",
    "lakes",
    "Main river barges move against the current without engines",
    "A new surface effect accelerates stationary vessels upstream. Freight operators remove fuel surcharges from one test route.",
    { Logistics: 1.5, Energy: -0.8, Industrial: 1 },
  ],
  [
    "fra_steel",
    "fra",
    "GLOBAL",
    "infrastructure",
    "German steel becomes lighter when assigned a higher credit rating",
    "Identical beams show different weights after financial certification. Construction firms request ratings alongside conventional material tests.",
    { Industrial: 1.7, Banking: 1.1, Mining: -0.8 },
  ],
  [
    "fra_week",
    "fra",
    "REGIONAL",
    "policy",
    "Germany pilots a nine-day week while retaining seven calendar names",
    "The two additional days are counted only inside certified workplaces. Exchanges keep their existing hours, creating a dispute over economic output per day.",
    { Industrial: 1.3, Retail: -0.6, Technology: 0.9 },
  ],
  [
    "fra_wind",
    "fra",
    "GLOBAL",
    "fuel",
    "Wind turbines generate more power when neighbouring turbines are offline",
    "A coordination effect reverses standard capacity assumptions. Grid planners reduce simultaneous operation and cancel selected expansion projects.",
    { Energy: 1.4, Industrial: -1.2, Mining: -0.6 },
  ],
  [
    "hkg_paper",
    "hkg",
    "GLOBAL",
    "policy",
    "Hong Kong recognises folded maps as transferable land titles",
    "Folded sections temporarily become adjacent in the physical city. Property lenders pause valuations near newly connected sites.",
    { Banking: -1.6, Logistics: 1.2, Retail: 1 },
  ],
  [
    "hkg_harbour",
    "hkg",
    "REGIONAL",
    "lakes",
    "Victoria Harbour develops a freshwater corridor through salt water",
    "A stable fresh-water lane appears between ferry routes. Shipping firms test lower-corrosion passages while utilities assess extraction rights.",
    { Logistics: 1.2, Industrial: 1.1, Energy: -0.6 },
  ],
  [
    "hkg_cloud",
    "hkg",
    "LOCAL",
    "clouds",
    "Clouds above Central begin mirroring stock exchange order volumes",
    "Cloud height changes in proportion to local trading activity. Meteorologists restrict their use as a financial forecasting instrument.",
    { Technology: 1.4, Banking: -0.8, Airlines: -0.6 },
  ],
  [
    "hkg_lift",
    "hkg",
    "REGIONAL",
    "infrastructure",
    "Hong Kong lifts connect neighbouring towers without horizontal tunnels",
    "Elevators now open onto different buildings at matching floor levels. Office demand shifts toward connected towers and away from road frontage.",
    { Industrial: 1.5, Logistics: 1, Retail: -0.6 },
  ],
  [
    "hkg_pearl",
    "hkg",
    "GLOBAL",
    "signal",
    "Cultured pearls demonstrate stable quantum memory at room temperature",
    "Laboratories reproduce the effect in commercial oyster farms. Electronics suppliers place orders before an industrial standard has been approved.",
    { Technology: 1.8, Semiconductors: -1.2, Retail: 0.7 },
  ],
  [
    "hkg_ferry",
    "hkg",
    "LOCAL",
    "rail",
    "Harbour ferry operator introduces a route that is longer on the return journey",
    "The water distance changes by three kilometres depending on direction. Navigation software receives an emergency asymmetrical-map update.",
    { Logistics: -1.2, Technology: 1.3, Energy: 0.7 },
  ],
  [
    "sha_sleep",
    "sha",
    "GLOBAL",
    "signal",
    "Shanghai factories report production on days that have not yet occurred",
    "Finished goods arrive carrying inspection records dated next week. Export authorities quarantine the shipments pending a time-of-origin rule.",
    { Industrial: 1.7, Logistics: -1.2, Banking: -0.8 },
  ],
  [
    "sha_port",
    "sha",
    "REGIONAL",
    "rail",
    "Shanghai port trials containers with greater internal than external volume",
    "Cargo capacity exceeds the physical dimensions of the new units. Insurers and customs officers introduce weight-only declarations for the pilot.",
    { Logistics: 1.8, Industrial: 1.2, Airlines: -0.8 },
  ],
  [
    "sha_sky",
    "sha",
    "LOCAL",
    "infrastructure",
    "Pudong tower gains floors whenever its reflection is visible in the river",
    "Only the reflected elevation changes at first, followed by the building itself. Inspectors temporarily cover the waterfront to stabilise the structure.",
    { Industrial: 1.2, Banking: -1.3, Technology: 0.8 },
  ],
  [
    "sha_salt",
    "sha",
    "GLOBAL",
    "fuel",
    "Chinese research group converts seawater salt into reusable solar cells",
    "The cells dissolve after use and can be re-formed without rare metals. Mining shares face substitution pressure as energy firms assess mass production.",
    { Energy: 1.7, Mining: -1.5, Semiconductors: -0.7 },
  ],
  [
    "sha_diplomacy",
    "sha",
    "REGIONAL",
    "policy",
    "Trade negotiators grant shipping routes temporary diplomatic citizenship",
    "Routes receive legal protection separate from the vessels using them. Logistics providers expect fewer interruptions, while governments dispute enforcement.",
    { Logistics: 1.4, Banking: 0.8, Energy: 0.5 },
  ],
  [
    "sha_bamboo",
    "sha",
    "GLOBAL",
    "crops",
    "Bamboo develops conductive channels suitable for low-voltage power grids",
    "Naturally connected stems distribute electricity across a test plantation. Industrial cable suppliers face competition from an agricultural production cycle.",
    { Energy: 1.3, Industrial: -1.1, Mining: -1.2 },
  ],
  [
    "sin_tide",
    "sin",
    "GLOBAL",
    "lakes",
    "Singapore stores an entire low tide in an underground reservoir",
    "Engineers isolate the water movement and release it on a separate timetable. Port operators and energy utilities bid for scheduled tidal windows.",
    { Energy: 1.7, Logistics: 1.3, Industrial: 1 },
  ],
  [
    "sin_rules",
    "sin",
    "REGIONAL",
    "policy",
    "Singapore replaces 400 licensing forms with one legally binding colour",
    "Applicants submit a calibrated colour sample representing their business risk. Technology firms develop compliance displays for overseas exporters.",
    { Technology: 1.4, Logistics: 1.1, Banking: -0.6 },
  ],
  [
    "sin_tree",
    "sin",
    "GLOBAL",
    "crops",
    "Tropical trees begin cooling nearby servers below ambient temperature",
    "A plant-based heat-transfer effect sharply reduces cooling demand. Data centres purchase nursery stock while utilities lower load forecasts.",
    { Technology: 1.8, Energy: -1.1, Industrial: -0.7 },
  ],
  [
    "sin_route",
    "sin",
    "REGIONAL",
    "rail",
    "Singapore ships arrive with cargo from a different destination but identical value",
    "A recurring route anomaly exchanges contents while preserving invoice totals. Operators suspend automated settlement until commodities can be tracked individually.",
    { Logistics: -1.7, Banking: -0.8, Technology: 1.4 },
  ],
  [
    "sin_rain",
    "sin",
    "LOCAL",
    "clouds",
    "Rain above Marina Bay stops falling and forms a suspended freshwater layer",
    "Aircraft reroute around the stable layer as engineers explore controlled harvesting. The city adds a second elevation to its weather map.",
    { Airlines: -1.2, Industrial: 1.3, Energy: 0.8 },
  ],
  [
    "sin_time",
    "sin",
    "GLOBAL",
    "signal",
    "Singapore sells verified microseconds recovered from idle processors",
    "A timing discrepancy allows unused computation intervals to be transferred between machines. Cloud providers introduce contracts for accumulated processing time.",
    { Technology: 1.7, Semiconductors: 1.3, Banking: 0.7 },
  ],
  [
    "dub_liberty",
    "dub",
    "GLOBAL",
    "policy",
    "Gulf states establish unrestricted movement and a regional freedom charter",
    "A new fictional federation removes residency restrictions and grants municipal assemblies wide powers. European capitals seek observer status as investment flows shift south.",
    { Banking: 1.5, Airlines: 1.6, Logistics: 1.2 },
  ],
  [
    "dub_sand",
    "dub",
    "GLOBAL",
    "signal",
    "Desert sand begins storing executable computer programs",
    "Silicon grains preserve logic without fabrication after exposure to a specific temperature cycle. Chipmakers seek exclusive extraction agreements.",
    { Technology: 1.8, Semiconductors: -1.5, Mining: 1.1 },
  ],
  [
    "dub_snow",
    "dub",
    "REGIONAL",
    "clouds",
    "Permanent snowfall declared over a single Dubai industrial district",
    "Snow remains stable despite surrounding heat. Cold-storage firms relocate, while utilities redistribute the district's former cooling capacity.",
    { Energy: -0.8, Logistics: 1.5, Retail: 1.1 },
  ],
  [
    "dub_horizon",
    "dub",
    "LOCAL",
    "infrastructure",
    "Dubai records a second coastline twenty metres above sea level",
    "A stable elevated water surface follows the existing shore without visible support. The municipality freezes waterfront permits pending a revised elevation survey.",
    { Banking: -1.3, Industrial: 1.6, Logistics: -0.6 },
  ],
  [
    "dub_oil",
    "dub",
    "GLOBAL",
    "fuel",
    "Gulf oil wells begin producing drinkable water with equivalent energy density",
    "Laboratory tests confirm that the liquid burns only inside certified turbines. Energy exporters debate whether existing oil treaties still apply.",
    { Energy: 1.8, Airlines: 1.2, Mining: -1 },
  ],
  [
    "dub_airport",
    "dub",
    "REGIONAL",
    "rail",
    "Dubai terminal begins boarding passengers directly into destination airports",
    "A limited gate trial bypasses aircraft while preserving border controls. Airlines seek compensation and operators review the definition of an air route.",
    { Airlines: -1.8, Logistics: 1.5, Retail: 1.1 },
  ],
  [
    "syd_cloud",
    "syd",
    "REGIONAL",
    "clouds",
    "Sydney buys a six-month lease on sunlight displaced from the Gulf",
    "Additional solar exposure arrives outside normal daylight hours. Grid operators schedule exports while local residents request new night-time standards.",
    { Energy: 1.5, Industrial: 0.8, Airlines: -0.5 },
  ],
  [
    "syd_reef",
    "syd",
    "GLOBAL",
    "crops",
    "Australian coral produces a biodegradable replacement for structural aluminium",
    "Marine trials yield a light, rigid material with rapid regrowth. Aerospace suppliers begin certification as metal producers reduce investment forecasts.",
    { Industrial: 1.5, Airlines: 1.1, Mining: -1.6 },
  ],
  [
    "syd_opera",
    "syd",
    "LOCAL",
    "signal",
    "Opera House sound waves remain measurable for three days after a performance",
    "Persistent vibrations can be collected and converted into electrical output. The venue signs its first energy purchase agreement.",
    { Energy: 1.3, Technology: 1.1, Retail: 0.6 },
  ],
  [
    "syd_harbour",
    "syd",
    "REGIONAL",
    "lakes",
    "Sydney Harbour depth doubles without any change in shoreline",
    "Survey vessels record a sudden vertical expansion. Port companies propose larger cargo calls while geologists investigate the additional water volume.",
    { Logistics: 1.6, Industrial: 1.2, Banking: -0.6 },
  ],
  [
    "syd_roads",
    "syd",
    "LOCAL",
    "infrastructure",
    "Sydney roads shorten in direct proportion to public transport occupancy",
    "The effect reverses when buses empty. Authorities add occupancy forecasts to navigation services and postpone a planned road expansion.",
    { Logistics: 1.3, Technology: 1.1, Industrial: -0.9 },
  ],
  [
    "syd_night",
    "syd",
    "GLOBAL",
    "policy",
    "Australia registers night-time as an exportable national resource",
    "A new treaty permits scheduling verified darkness in partner regions. Solar investors and airlines seek exemptions from the proposed allocation system.",
    { Banking: 1.1, Energy: -1.3, Airlines: -0.8 },
  ],
  [
    "tor_ice",
    "tor",
    "GLOBAL",
    "fuel",
    "Canadian lake ice retains winter temperatures throughout summer",
    "The material remains frozen without absorbing surrounding heat. Energy-intensive cooling industries begin negotiating long-term storage contracts.",
    { Energy: -1.3, Logistics: 1.5, Industrial: 1.2 },
  ],
  [
    "tor_maple",
    "tor",
    "GLOBAL",
    "crops",
    "Maple sap replaces copper in commercial conductivity tests",
    "The processed sap transports electricity with lower losses than conventional wire. Mining groups seek partnerships with forestry operators.",
    { Mining: -1.6, Energy: 1.2, Technology: 1.4 },
  ],
  [
    "tor_tower",
    "tor",
    "LOCAL",
    "signal",
    "CN Tower receives broadcasts from cities thirty minutes in the future",
    "Signals match subsequent local broadcasts in controlled tests. Financial regulators prohibit their use pending an information-access ruling.",
    { Technology: 1.6, Banking: -1.4, Semiconductors: 1 },
  ],
  [
    "tor_border",
    "tor",
    "REGIONAL",
    "policy",
    "Canada and the United States trial a border that moves with the weather",
    "A monitored corridor changes jurisdiction according to local temperature. Retailers and logistics firms request hourly tax and customs feeds.",
    { Technology: 1.4, Logistics: -1.2, Retail: -0.8 },
  ],
  [
    "tor_rail",
    "tor",
    "LOCAL",
    "rail",
    "Toronto streetcars recharge by collecting abandoned mobile data",
    "A power converter extracts energy from expired wireless transmissions. Transit operators partner with telecom firms to map dense coverage routes.",
    { Energy: 1.1, Technology: 1.5, Automotive: 0.8 },
  ],
  [
    "tor_snow",
    "tor",
    "REGIONAL",
    "clouds",
    "Toronto snow crystals encode complete architectural drawings",
    "Recovered patterns correspond to viable low-cost housing plans. Developers seek licences while authorities investigate authorship.",
    { Industrial: 1.6, Banking: 0.8, Technology: -0.5 },
  ],
  [
    "mum_monsoon",
    "mum",
    "GLOBAL",
    "clouds",
    "Mumbai monsoon begins depositing industrially refined copper",
    "Rainwater tests show consistent metal purity across a wide corridor. International exchanges revise storage rules for liquid mineral deliveries.",
    { Mining: -1.6, Industrial: 1.3, Energy: 1.1 },
  ],
  [
    "mum_train",
    "mum",
    "REGIONAL",
    "rail",
    "Mumbai commuter network gains capacity without adding carriages",
    "Internal measurements show an extra aisle for every hundred passengers. Operators commission independent safety and spatial audits.",
    { Logistics: 1.7, Industrial: -0.7, Technology: 1 },
  ],
  [
    "mum_memory",
    "mum",
    "GLOBAL",
    "signal",
    "Indian software companies deliver updates through synchronised radio silence",
    "Devices install verified packages during scheduled transmission gaps. Network providers and chipmakers reassess infrastructure requirements.",
    { Technology: 1.7, Semiconductors: -1.1, Industrial: -0.5 },
  ],
  [
    "mum_currency",
    "mum",
    "REGIONAL",
    "policy",
    "Indian coastal cities adopt a currency backed by predictable rainfall",
    "Reserve certificates track independently verified monsoon volumes. Banks offer weather-linked deposit products while importers seek conversion guarantees.",
    { Banking: 1.4, Technology: 1.1, Retail: -0.6 },
  ],
  [
    "mum_land",
    "mum",
    "LOCAL",
    "infrastructure",
    "Mumbai shoreline extends after every successful land registry correction",
    "Resolved title disputes produce measurable new coastal ground. Authorities suspend bulk applications while surveyors reconcile property records.",
    { Industrial: 1.5, Banking: -1.2, Logistics: 0.9 },
  ],
  [
    "mum_silk",
    "mum",
    "GLOBAL",
    "crops",
    "Indian silk fibres replace rare metals in next-generation batteries",
    "The fibre structure stores charge without conventional mineral electrodes. Battery firms invest in sericulture as mining contracts weaken.",
    { Automotive: 1.6, Energy: 1.4, Mining: -1.7 },
  ],
  [
    "sao_forest",
    "sao",
    "GLOBAL",
    "crops",
    "Brazilian forests begin producing processed building timber without felling",
    "Mature trees release finished beams from their outer bark. Construction buyers increase orders while machinery demand shifts away from harvesting equipment.",
    { Industrial: 1.6, Logistics: 1.1, Mining: -0.6 },
  ],
  [
    "sao_river",
    "sao",
    "REGIONAL",
    "lakes",
    "Tietê river removes pollutants from neighbouring rivers without a physical connection",
    "Contamination falls across independently monitored catchments. Utilities commission controlled trials and suspend selected treatment plant expansions.",
    { Industrial: -1.1, Technology: 1.4, Energy: -0.6 },
  ],
  [
    "sao_cloud",
    "sao",
    "LOCAL",
    "clouds",
    "São Paulo clouds begin following commercial property boundaries",
    "Rain falls precisely within registered parcels. Property managers seek weather clauses and insurers replace regional models with title-by-title forecasts.",
    { Banking: -1.2, Technology: 1.3, Retail: 0.7 },
  ],
  [
    "sao_fuel",
    "sao",
    "GLOBAL",
    "fuel",
    "Brazil reclassifies coffee reserves as strategic transport infrastructure",
    "Following successful engine trials, coffee extraction becomes subject to energy export rules. Fuel refiners and food retailers compete for the same reserves.",
    { Energy: 1.7, Retail: -1.3, Automotive: 1.1 },
  ],
  [
    "sao_length",
    "sao",
    "LOCAL",
    "infrastructure",
    "Paulista Avenue gains usable office frontage each time its name is spoken",
    "A measured expansion stops overnight when references decline. Authorities limit automated address broadcasts while property records are audited.",
    { Industrial: 1.2, Banking: -1.2, Technology: 0.8 },
  ],
  [
    "sao_vote",
    "sao",
    "REGIONAL",
    "policy",
    "South American trade bloc grants voting rights to major river basins",
    "Independent ecological measurements determine each basin's policy preferences. Shipping and mining permits enter a new approval process.",
    { Mining: -1.3, Logistics: -0.9, Technology: 1.2 },
  ],
];
const places: Record<string, string> = {
  ist: "Istanbul",
  lon: "London",
  par: "Paris",
  tok: "Tokyo",
  nyc: "New York",
  nai: "Nairobi",
  fra: "Frankfurt",
  hkg: "Hong Kong",
  sha: "Shanghai",
  sin: "Singapore",
  dub: "Dubai",
  syd: "Sydney",
  tor: "Toronto",
  mum: "Mumbai",
  sao: "São Paulo",
};
const categories: Partial<Record<SceneKind, string>> = {
  fuel: "Energy transition",
  rail: "Transport",
  policy: "Politics & regulation",
  signal: "Technology",
  crops: "Resources",
  infrastructure: "Urban development",
  lakes: "Geography",
  clouds: "Climate",
  coffee: "Commodities",
};
export const expandedNewswire: Record<string, OddScenario> = Object.fromEntries(
  rows.map(([id, hub, scope, scene, headline, body, effects]) => {
    const up = Object.entries(effects)
        .filter(([, v]) => v > 0)
        .map(([k]) => k.toLowerCase()),
      down = Object.entries(effects)
        .filter(([, v]) => v < 0)
        .map(([k]) => k.toLowerCase());
    return [
      id,
      {
        hub,
        scope,
        scene,
        category: categories[scene] ?? "World affairs",
        headline,
        body,
        consequence:
          (up.length
            ? "Demand and investment support " + up.join(", ") + ". "
            : "") +
          (down.length
            ? "Substitution, financing or operational risk weighs on " +
              down.join(", ") +
              ". "
            : "") +
          "The effect reaches " +
          (scope === "GLOBAL"
            ? "connected exchanges worldwide"
            : scope === "REGIONAL"
              ? "other exchanges in the region"
              : "companies operating in this city") +
          ".",
        effects,
        captions: [
          places[hub] + " / correspondent reconstruction",
          categories[scene] + " / initial assessment",
          "Market response / " + up.slice(0, 2).join(" + "),
        ],
      },
    ];
  }),
);
